<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-PAON71K" name="API_Tests.StudentsList_createNewStudent" tests="3" failures="1" timestamp="11 Sep 2019 15:57:17 GMT" time="2.994" errors="0">
  <testcase name="Test001_verifyStudentCreated" time="2.436" classname="API_Tests.StudentsList_createNewStudent"/>
  <testcase name="Test002_verifyStudentUpdated" time="0.377" classname="API_Tests.StudentsList_createNewStudent"/>
  <testcase name="Test003_verifyStudentDeleted" time="0.181" classname="API_Tests.StudentsList_createNewStudent">
    <failure type="java.lang.AssertionError" message="String semper@nequesed.co.uk IS exist inside the overall text, see details: java.lang.AssertionError: expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: String semper@nequesed.co.uk IS exist inside the overall text, see details: java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at extensions.verify.NOTcontains(verify.java:149)
at API_Tests.StudentsList_createNewStudent.Test003_verifyStudentDeleted(StudentsList_createNewStudent.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test003_verifyStudentDeleted -->
</testsuite> <!-- API_Tests.StudentsList_createNewStudent -->
